version: '3.8'

services:
  firebase-emulator:
    image: andreysenov/firebase-tools:latest
    container_name: carrent-firebase-emulator
    ports:
      - "4000:4000"
      - "9099:9099"
      - "9000:9000"
      - "9199:9199"
    volumes:
      - ./firebase:/workspace
    command: firebase emulators:start --project carrent-2556e